<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>AzubiApp</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>AzubiApp</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.azubiapp</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>


	<ItemGroup>
		<Resx Include="Resources\Localization\AppResources.de.resx" />
		<Resx Include="Resources\Localization\AppResources.resx" />
	</ItemGroup>
	
	<ItemGroup>
		<!-- App Icon -->
	
		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Images\logo_white.png" Color="#000000" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\AppIcon\REMIRA_figurative_mark_white.png" />
	  <None Remove="Resources\Icons\home.svg" />
	  <None Remove="Resources\Icons\quiz.svg" />
	  <None Remove="Resources\Icons\study.svg" />
	  <None Remove="Resources\Icons\user.svg" />
	  <None Remove="Resources\MipMap\logoicon.png" />
	</ItemGroup>

	<ItemGroup>
	  <MauiImage Include="Resources\Icons\einstellungen.svg">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </MauiImage>
	  <MauiImage Include="Resources\Icons\home.svg">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	    <CustomToolNamespace>home.svg</CustomToolNamespace>
	  </MauiImage>
	  <MauiImage Include="Resources\Icons\quiz.svg">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	    <CustomToolNamespace>quiz.svg</CustomToolNamespace>
	  </MauiImage>
	  <MauiImage Include="Resources\Icons\study.svg">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	    <CustomToolNamespace>study.svg</CustomToolNamespace>
	  </MauiImage>
	  <MauiImage Include="Resources\Icons\user.svg">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	    <CustomToolNamespace>user.svg</CustomToolNamespace>
	  </MauiImage>
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_132_balk_1.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_123_balk_2.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_116_balk_3.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_115_best_1.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_140_grenz_1.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_135_para_1.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_133_warn_1.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_134_warn_2.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_136_warn_3.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_137_warn_4.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_138_warn_5.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_139_warn_6.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_141_warn_7.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_091_wbz_1.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_127_wbz_2.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_128_wbz_3.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_129_wbz_4.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_130_wbz_5.png" />
	  <MauiImage Include="Resources\Images\QuestionsImage\De\question_131_wbz_6.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="11.1.0" />
		<PackageReference Include="EntityFramework" Version="6.5.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.2" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.30" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.LiveShare" Version="1.1.57" />
		<PackageReference Include="RESXManager" Version="1.7.0" />
		<PackageReference Include="ServiceStack.Interfaces" Version="8.6.0" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resources\Translate\AppResources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>AppResources.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Views\EinstellungPage.xaml.cs">
	    <DependentUpon>EinstellungPage.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\Translate\AppResources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Views\MainPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ModulePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\EinstellungPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\QuizPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ResultsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\UseCasesPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup>
		<MauiAsset Include="html\**\*.*" />
	  <MauiIcon Include="Resources\MipMap\logoicon.png" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Resources\Images\QuestionsImage\En\" />
	</ItemGroup>

</Project>
