//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzubiApp.Resources.Translate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzubiApp.Resources.Translate.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlertError.
        /// </summary>
        internal static string AlertError {
            get {
                return ResourceManager.GetString("AlertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlertLeaveQuiz.
        /// </summary>
        internal static string AlertLeaveQuiz {
            get {
                return ResourceManager.GetString("AlertLeaveQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlertNo.
        /// </summary>
        internal static string AlertNo {
            get {
                return ResourceManager.GetString("AlertNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlertResetProgress.
        /// </summary>
        internal static string AlertResetProgress {
            get {
                return ResourceManager.GetString("AlertResetProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlertSelect.
        /// </summary>
        internal static string AlertSelect {
            get {
                return ResourceManager.GetString("AlertSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlertYes.
        /// </summary>
        internal static string AlertYes {
            get {
                return ResourceManager.GetString("AlertYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppShellHomeButton.
        /// </summary>
        internal static string AppShellHomeButton {
            get {
                return ResourceManager.GetString("AppShellHomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppShellSettingsButton.
        /// </summary>
        internal static string AppShellSettingsButton {
            get {
                return ResourceManager.GetString("AppShellSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackModuleButton.
        /// </summary>
        internal static string BackModuleButton {
            get {
                return ResourceManager.GetString("BackModuleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackQuizButton.
        /// </summary>
        internal static string BackQuizButton {
            get {
                return ResourceManager.GetString("BackQuizButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackToStartButton.
        /// </summary>
        internal static string BackToStartButton {
            get {
                return ResourceManager.GetString("BackToStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeLanguageButton.
        /// </summary>
        internal static string ChangeLanguageButton {
            get {
                return ResourceManager.GetString("ChangeLanguageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckButton.
        /// </summary>
        internal static string CheckButton {
            get {
                return ResourceManager.GetString("CheckButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionsButton.
        /// </summary>
        internal static string ConditionsButton {
            get {
                return ResourceManager.GetString("ConditionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueQuizButton.
        /// </summary>
        internal static string ContinueQuizButton {
            get {
                return ResourceManager.GetString("ContinueQuizButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CorrectAnswerTitle.
        /// </summary>
        internal static string CorrectAnswerTitle {
            get {
                return ResourceManager.GetString("CorrectAnswerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilterButton.
        /// </summary>
        internal static string FilterButton {
            get {
                return ResourceManager.GetString("FilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinishButton.
        /// </summary>
        internal static string FinishButton {
            get {
                return ResourceManager.GetString("FinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForecastButton.
        /// </summary>
        internal static string ForecastButton {
            get {
                return ResourceManager.GetString("ForecastButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralButton.
        /// </summary>
        internal static string GeneralButton {
            get {
                return ResourceManager.GetString("GeneralButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainPageOpenButton.
        /// </summary>
        internal static string MainPageOpenButton {
            get {
                return ResourceManager.GetString("MainPageOpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainPageProgressText.
        /// </summary>
        internal static string MainPageProgressText {
            get {
                return ResourceManager.GetString("MainPageProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainPageUseCaseTitle.
        /// </summary>
        internal static string MainPageUseCaseTitle {
            get {
                return ResourceManager.GetString("MainPageUseCaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NextQuizButton.
        /// </summary>
        internal static string NextQuizButton {
            get {
                return ResourceManager.GetString("NextQuizButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderButton.
        /// </summary>
        internal static string OrderButton {
            get {
                return ResourceManager.GetString("OrderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterButton.
        /// </summary>
        internal static string ParameterButton {
            get {
                return ResourceManager.GetString("ParameterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuizSubtitle.
        /// </summary>
        internal static string QuizSubtitle {
            get {
                return ResourceManager.GetString("QuizSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultPageCorrectAnswersText.
        /// </summary>
        internal static string ResultPageCorrectAnswersText {
            get {
                return ResourceManager.GetString("ResultPageCorrectAnswersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultPageYourAnswersText.
        /// </summary>
        internal static string ResultPageYourAnswersText {
            get {
                return ResourceManager.GetString("ResultPageYourAnswersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultTitle.
        /// </summary>
        internal static string ResultTitle {
            get {
                return ResourceManager.GetString("ResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopicsQuizButton.
        /// </summary>
        internal static string TopicsQuizButton {
            get {
                return ResourceManager.GetString("TopicsQuizButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseAbcAnalysisButton.
        /// </summary>
        internal static string UseCaseAbcAnalysisButton {
            get {
                return ResourceManager.GetString("UseCaseAbcAnalysisButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseAutoStoreButton.
        /// </summary>
        internal static string UseCaseAutoStoreButton {
            get {
                return ResourceManager.GetString("UseCaseAutoStoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseBackButton.
        /// </summary>
        internal static string UseCaseBackButton {
            get {
                return ResourceManager.GetString("UseCaseBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseBufferStoreButton.
        /// </summary>
        internal static string UseCaseBufferStoreButton {
            get {
                return ResourceManager.GetString("UseCaseBufferStoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseCompositeOrderButton.
        /// </summary>
        internal static string UseCaseCompositeOrderButton {
            get {
                return ResourceManager.GetString("UseCaseCompositeOrderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseContainerOptimizationButton.
        /// </summary>
        internal static string UseCaseContainerOptimizationButton {
            get {
                return ResourceManager.GetString("UseCaseContainerOptimizationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseContractsButton.
        /// </summary>
        internal static string UseCaseContractsButton {
            get {
                return ResourceManager.GetString("UseCaseContractsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseDueDatesButton.
        /// </summary>
        internal static string UseCaseDueDatesButton {
            get {
                return ResourceManager.GetString("UseCaseDueDatesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseFilterClassesButton.
        /// </summary>
        internal static string UseCaseFilterClassesButton {
            get {
                return ResourceManager.GetString("UseCaseFilterClassesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseGeneralHandlingButton.
        /// </summary>
        internal static string UseCaseGeneralHandlingButton {
            get {
                return ResourceManager.GetString("UseCaseGeneralHandlingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseInheritanceButton.
        /// </summary>
        internal static string UseCaseInheritanceButton {
            get {
                return ResourceManager.GetString("UseCaseInheritanceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseOrderRhythmButton.
        /// </summary>
        internal static string UseCaseOrderRhythmButton {
            get {
                return ResourceManager.GetString("UseCaseOrderRhythmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCasePartitionButton.
        /// </summary>
        internal static string UseCasePartitionButton {
            get {
                return ResourceManager.GetString("UseCasePartitionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCasePrecursorButton.
        /// </summary>
        internal static string UseCasePrecursorButton {
            get {
                return ResourceManager.GetString("UseCasePrecursorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCasePromotionsButton.
        /// </summary>
        internal static string UseCasePromotionsButton {
            get {
                return ResourceManager.GetString("UseCasePromotionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseResubmissionButton.
        /// </summary>
        internal static string UseCaseResubmissionButton {
            get {
                return ResourceManager.GetString("UseCaseResubmissionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseSftTypesButton.
        /// </summary>
        internal static string UseCaseSftTypesButton {
            get {
                return ResourceManager.GetString("UseCaseSftTypesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseSplitConditionsButton.
        /// </summary>
        internal static string UseCaseSplitConditionsButton {
            get {
                return ResourceManager.GetString("UseCaseSplitConditionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseSporadicProcedureButton.
        /// </summary>
        internal static string UseCaseSporadicProcedureButton {
            get {
                return ResourceManager.GetString("UseCaseSporadicProcedureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCasesSubtitle.
        /// </summary>
        internal static string UseCasesSubtitle {
            get {
                return ResourceManager.GetString("UseCasesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseTransferButton.
        /// </summary>
        internal static string UseCaseTransferButton {
            get {
                return ResourceManager.GetString("UseCaseTransferButton", resourceCulture);
            }
        }
    }
}
